include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = appstub
appstub_OBJC_FILES = appstub.m
appstub_LDFLAGS += -lgnustep-gui

CC = clang
ADDITIONAL_OBJCFLAGS = -Wall -Wextra -Werror -O2

include $(GNUSTEP_MAKEFILES)/tool.make
