include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = ItemFlowDemo

ItemFlowDemo_OBJC_FILES = main.m AppDelegate.m ../ItemFlowView.m
ItemFlowDemo_RESOURCE_DIRS = 

ADDITIONAL_OBJCFLAGS += -fobjc-arc -fobjc-arc-exceptions -I..
ADDITIONAL_LDFLAGS += -lGL -lGLU

include $(GNUSTEP_MAKEFILES)/application.make
