#!/bin/sh

# Run before everything else; loginwindow waits until /tmp is mounted and then starts X server and shows the login screen
# PROVIDE: loginwindow
# REQUIRE:
# BEFORE:
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable the LoginWindow:
#
# loginwindow_enable="YES"
#

. /etc/rc.subr
. /System/Library/Makefiles/GNUstep.sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

name="loginwindow"
rcvar=loginwindow_enable

load_rc_config ${name}

: ${loginwindow_enable:="NO"}

command="/usr/sbin/daemon"
procname="/System/Applications/LoginWindow.app/LoginWindow"
pidfile="/var/run/${name}.pid"
logfile="/var/log/LoginWindow.log"
rm -f ${logfile}
touch ${logfile}
chmod 644 ${logfile}
command_args="-r -f -o ${logfile} ${procname} --pid-file=${pidfile}"

run_rc_command "$1"
